FF: 
  # Setup parameters.
  pointCloud_fileName: /home/erwin/catkin_ws/src/FloodFill_For_LiDAR/1629379207.388575077.pcd
  IMAGE_WIDTH: 2048
  IMAGE_HEIGHT: 64

  bufferSize: 30
  sampleFactor: 1

  # FloodFill parameters.
  pointThresholdFloodFill_min: 0.001 
  pointThresholdFloodFill_max: 0.1 
  c_point: 0.1 

  normalSampleDistance_min: 4.0
  normalSampleDistance_max: 20.0
  c_range: 1.0 

  planeThresholdFloodFill_flood: 0.0001 
  planeThresholdFloodFill_merge: 0.01 
  planeThresholdFloodFill_flood_max: 0.01 
  planeThresholdFloodFill_merge_max: 0.1 
  angleThresholdFloodFill: 0.05 
  angleThresholdFloodFill_max: 0.2 
  minPlaneSize: 1000 
  # c_plane: 1
  c_plane: 1.5 
  # c_plane_merge: 1 
  c_plane_merge: 8 
  # c_angle: 1
  c_angle: 2 
